const mongoose = require("mongoose");

const itemSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  type: { type: String, enum: ["lost", "found"], required: true },
  title: { type: String, required: true },
  category: { type: String, required: true },
  location: { type: String, required: true },
  desc: { type: String, required: true },
  photos: [{ type: String }],  // Cloudinary URLs
  contact: { type: String, required: true },
  reward: { type: String, default: "" },
  status: { type: String, enum: ["active", "claimed"], default: "active" },
  // CLIP image embedding (512-dim vector) generated by the Python
  // image-service, used to suggest matches between lost <-> found items.
  embedding: { type: [Number], default: undefined, select: false },
}, { timestamps: true });

module.exports = mongoose.model("Item", itemSchema);